# Switched to 'midnight' Jekyll theme: https://github.com/pages-themes/midnight#usage
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# Fix [Link](README.md) => <a href="README.html">Link</a>
# - jekyll-relative-links
# - jekyll-optional-front-matter

# EXCLUDE FILES & FOLDERS FROM BUILD: 
exclude: 
  - curriculum/TBP/
  - curriculum/modules/
  - app
  - components
  - public
  - tools
  
# CUSTOM _SASS FOLDER: https://github.com/jekyll/jekyll-sass-converter#configuration-options, https://jekyllrb.com/docs/configuration/sass/
sass:
  sass_dir: assets/jekyll/_sass

# CUSTOM _includes FOLDER: https://jekyllrb.com/docs/configuration/options/#build-command-options
layouts_dir:  assets/jekyll/_layouts
includes_dir: assets/jekyll/_includes

