name: "Week 08 - Day 5 JavaScript Core 2 | Test Exercise: 'Test your skills: JavaScript Arrays'"
on:
  push:
    branches:
      - 'main'
    paths:
      - user/week08/exercises/day05/task_5/**
jobs:
  task_5:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: "Test Exercise: 'Test your skills: JavaScript Arrays' > Check solution files existence"
        uses: andstor/file-existence-action@v2
        with:
          files: "user/week08/exercises/day05/task_5/arrays-skills.js, user/week08/exercises/day05/task_5/arrays-skills.html"
          fail: true